/**
 * ASDM Emit Adapter — Base Interface and Shared Helpers
 * 
 * Each adapter converts canonical .asdm.md assets into provider-native
 * file formats. The interface is simple and composable.
 */

import { hashString } from '../core/hash.js'
import type { ParsedAsset } from '../core/parser.js'
import type { ResolvedProfile } from '../core/profile-resolver.js'

export type { ParsedAsset, ResolvedProfile }

export interface EmittedFile {
  relativePath: string    // e.g., ".opencode/agents/code-reviewer.md"
  content: string | Buffer
  sha256: string
  adapter: string         // Adapter name (e.g., "opencode", "claude-code")
  sourcePath: string      // Registry-relative source (e.g., "agents/code-reviewer.asdm.md")
}

export interface EmitAdapter {
  readonly name: string

  /** Convert a canonical agent .asdm.md to provider-native format */
  emitAgent(parsed: ParsedAsset, targetDir: string): EmittedFile[]

  /** Convert a canonical skill .asdm.md to provider-native format */
  emitSkill(parsed: ParsedAsset, targetDir: string): EmittedFile[]

  /** Convert a canonical command .asdm.md to provider-native format */
  emitCommand(parsed: ParsedAsset, targetDir: string): EmittedFile[]

  /**
   * Generate the root instructions file for this provider.
   * (AGENTS.md, CLAUDE.md, .github/copilot-instructions.md, etc.)
   */
  emitRootInstructions(profile: ResolvedProfile, targetDir: string): EmittedFile[]

  /**
   * Generate the provider config file.
   * (.opencode/opencode.jsonc, .claude/settings.json, etc.)
   */
  emitConfig(profile: ResolvedProfile, targetDir: string): EmittedFile[]

  /**
   * Async variant of emitConfig — preferred when I/O detection is needed
   * (e.g. checking whether .json already exists before choosing extension).
   * If present, the syncer will call this instead of emitConfig.
   */
  emitConfigAsync?(profile: ResolvedProfile, targetDir: string): Promise<EmittedFile[]>
}

/** Create an EmittedFile from path and string content */
export function createEmittedFile(
  relativePath: string,
  content: string,
  adapter: string,
  sourcePath: string
): EmittedFile {
  return {
    relativePath,
    content,
    sha256: hashString(content),
    adapter,
    sourcePath,
  }
}

/** Generate a managed-file header comment for text files */
export function managedFileHeader(provider: string): string {
  return [
    `# ⚠️  ASDM MANAGED FILE — DO NOT EDIT MANUALLY`,
    `# This file is generated by asdm. Changes will be overwritten on next sync.`,
    `# To modify: edit the source in your asdm-registry and run \`asdm sync\`.`,
    `# Provider: ${provider}`,
    `#`,
  ].join('\n')
}

/** Generate a managed-file header for JSON/JSONC files */
export function managedJsonHeader(provider: string): string {
  return [
    `// ⚠️  ASDM MANAGED FILE — DO NOT EDIT MANUALLY`,
    `// This file is generated by asdm. Changes will be overwritten on next sync.`,
    `// To modify: edit the source in your asdm-registry and run \`asdm sync\`.`,
    `// Provider: ${provider}`,
    `//`,
  ].join('\n')
}

/**
 * Strip the managed-file header from content (for testing round-trips).
 * Returns content as-is if no header found.
 */
export function stripManagedHeader(content: string): string {
  const lines = content.split('\n')
  const headerEnd = lines.findIndex(
    (line, i) => i > 0 && !line.startsWith('#') && !line.startsWith('//')
  )
  if (headerEnd <= 0) return content
  return lines.slice(headerEnd).join('\n').trimStart()
}
