/**
 * Manifest Parser and Comparator
 *
 * The manifest.json is generated by CI and contains:
 *   - Version and build metadata
 *   - Corporate policy (locked fields)
 *   - Profile definitions
 *   - Asset checksums (SHA-256) and versions
 */

import { readJson, writeJson } from '../utils/fs.js'
import type { CorporatePolicy } from './config.js'

export interface ManifestAsset {
  sha256: string
  size: number
  version: string
}

export interface ManifestProfile {
  extends?: string[]
  agents?: string[]
  skills?: string[]
  commands?: string[]
  providers?: string[]
}

export interface AsdmManifest {
  $schema?: string
  version: string
  built_at: string
  commit_sha: string
  policy: CorporatePolicy
  profiles: Record<string, ManifestProfile>
  assets: Record<string, ManifestAsset>
}

/** Diff result between local (lockfile) and remote (manifest) */
export interface ManifestDiff {
  added: string[]      // Assets in manifest but not in lockfile
  updated: string[]    // Assets in both but with different sha256
  removed: string[]    // Assets in lockfile but not in manifest
  unchanged: string[]  // Assets identical in both
}

/**
 * Compute the diff between a remote manifest and local file state.
 *
 * @param manifest - Remote manifest from registry
 * @param localShas - Map of asset path → sha256 from lockfile (empty if no lockfile)
 * @param assetPaths - Which assets to diff (filtered by resolved profile)
 */
export function diffManifest(
  manifest: AsdmManifest,
  localShas: Record<string, string>,
  assetPaths: string[]
): ManifestDiff {
  const added: string[] = []
  const updated: string[] = []
  const removed: string[] = []
  const unchanged: string[] = []

  for (const assetPath of assetPaths) {
    const manifestAsset = manifest.assets[assetPath]
    if (!manifestAsset) continue  // Asset not in manifest (shouldn't happen)

    const localSha = localShas[assetPath]

    if (!localSha) {
      added.push(assetPath)
    } else if (localSha !== manifestAsset.sha256) {
      updated.push(assetPath)
    } else {
      unchanged.push(assetPath)
    }
  }

  // Find removed: in local but not in manifest assets for this profile
  for (const assetPath of Object.keys(localShas)) {
    if (!assetPaths.includes(assetPath) && !manifest.assets[assetPath]) {
      removed.push(assetPath)
    }
  }

  return { added, updated, removed, unchanged }
}

/**
 * Get all asset paths required by a resolved profile.
 */
export function getProfileAssetPaths(
  manifest: AsdmManifest,
  agentNames: string[],
  skillNames: string[],
  commandNames: string[]
): string[] {
  const paths: string[] = []

  for (const name of agentNames) {
    const path = `agents/${name}.asdm.md`
    if (manifest.assets[path]) paths.push(path)
  }

  for (const name of skillNames) {
    const path = `skills/${name}/SKILL.asdm.md`
    if (manifest.assets[path]) paths.push(path)
  }

  for (const name of commandNames) {
    const path = `commands/${name}.asdm.md`
    if (manifest.assets[path]) paths.push(path)
  }

  return paths
}

/** Load a cached manifest from local cache directory */
export async function loadCachedManifest(cacheDir: string): Promise<AsdmManifest | null> {
  return readJson<AsdmManifest>(`${cacheDir}/manifest.json`)
}

/** Save manifest to local cache */
export async function saveManifestToCache(cacheDir: string, manifest: AsdmManifest): Promise<void> {
  await writeJson(`${cacheDir}/manifest.json`, manifest)
}

/** Validate that a manifest has the required fields */
export function validateManifest(manifest: unknown): manifest is AsdmManifest {
  if (!manifest || typeof manifest !== 'object') return false
  const m = manifest as Record<string, unknown>
  return (
    typeof m['version'] === 'string' &&
    typeof m['built_at'] === 'string' &&
    typeof m['commit_sha'] === 'string' &&
    typeof m['policy'] === 'object' &&
    typeof m['profiles'] === 'object' &&
    typeof m['assets'] === 'object'
  )
}
